#!/bin/bash

#
# Preserve quotes. Apply quotes to the arguments that 
# require it.
#
arguments=""
need_quotes=0
for arg in "$@" 
do
    if [[ $arg == "-f" ]] || [[ $arg == "--filter" ]] ||\
       [[ $arg == "-i" ]] || [[ $arg == "--input" ]];
    then
        arguments=$arguments"$arg "
        need_quotes=1
        continue
    fi

    if [[ $need_quotes == 1 ]];
    then
        arguments=$arguments"\"$arg\" "
        need_quotes=0   
    else
        arguments=$arguments"$arg "
    fi
done

# Run dmine.
python main.py $arguments


